name: PR CI – pnpm · Lint · Build · Test

# -------------------------------------------------------------------------
# Triggers
# -------------------------------------------------------------------------
on:
  push:
    branches: [master]       # run CI when commits land on master
  pull_request:              # run on every PR event (open, sync, reopen, etc.)
  workflow_dispatch: {}

# -------------------------------------------------------------------------
# Jobs
# -------------------------------------------------------------------------

jobs:
  #-----------------------------------------------------------------------
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm first so setup‑node's pnpm cache doesn't fail
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node 20.x & enable pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install

      - name: ESLint
        run: pnpm lint

  #-----------------------------------------------------------------------
  build:
    name: Build Check
    needs: lint          # Run only if lint job passed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node 20.x & pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install

      - name: Build (Next 15 + Vite)
        run: pnpm build

  #-----------------------------------------------------------------------
  test:
    name: Test Check
    needs: lint          # Run in parallel with build once lint passes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node 20.x & pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install

      - name: Unit tests (Vitest)
        run: pnpm test